#pragma once

DEF_LUACFUNC(Delay);

DEF_LUACFUNC(KeyPress);
DEF_LUACFUNC(KeyDown);
DEF_LUACFUNC(KeyUp);

DEF_LUACFUNC(MoveTo);
DEF_LUACFUNC(LClick);
DEF_LUACFUNC(LDClick);
DEF_LUACFUNC(LDown);
DEF_LUACFUNC(LUp);
DEF_LUACFUNC(RClick);
DEF_LUACFUNC(RDown);
DEF_LUACFUNC(RUp);
DEF_LUACFUNC(MClick);
DEF_LUACFUNC(MDown);
DEF_LUACFUNC(MUp);

DEF_LUACFUNC(FindProcess);
DEF_LUACFUNC(KillProcess);
DEF_LUACFUNC(PixelColor);
DEF_LUACFUNC(RGB_);
DEF_LUACFUNC(UnRGB);
DEF_LUACFUNC(MsgBox);
DEF_LUACFUNC(FindWindow_);
DEF_LUACFUNC(MoveWindow_);
DEF_LUACFUNC(WindowPos);
DEF_LUACFUNC(Log);



int RegisterFunctions(CLuaSe& l);
